<?php

use Illuminate\Support\Facades\Auth;
use Livewire\Volt\Component;
use PragmaRX\Recovery\Recovery;

new class extends Component {
    public $secret;
    public $qrCodeUrl;
    public $showingQrCode = false;
    public $showingRecoveryCodes = false;
    public $recoveryCodes = [];
    public $code;
    public function mount()
    {
        $google2fa = app('pragmarx.google2fa');

        $user = Auth::user();
        $this->secret = $user->two_factor_secret;
        $this->recoveryCodes = $user->two_factor_recovery_codes;
        if (! $this->secret) {
            $this->secret = $google2fa->generateSecretKey();
            $this->recoveryCodes = (new Recovery())->toJson();
            $this->qrCodeUrl = $google2fa->getQRCodeInline(
                config('app.name'),
                $user->email,
                $this->secret
            );
        }
    }
    public function toggleQrCode()
    {
        $this->showingQrCode = ! $this->showingQrCode;
    }
    public function toggleRecoveryCodes()
    {
        $this->showingRecoveryCodes = ! $this->showingRecoveryCodes;
    }
    public function enableTwoFactor()
    {
        $google2fa = app('pragmarx.google2fa');
        $this->validate([
            'code' => ['required', 'digits:6', function ($attribute, $value, $fail) use ($google2fa) {
                if (! $google2fa->verifyKey($this->secret, $value)) {
                    $fail(__('The :attribute is invalid.'));
                }
            }],
        ]);

        $user = Auth::user();
        $user->two_factor_secret = $this->secret;
        $user->two_factor_recovery_codes = $this->recoveryCodes;
        $user->two_factor_confirmed_at = now();
        $user->save();

        $this->dispatch('done', success: "Two Factor Authentication Enabled");
    }
    public function disableTwoFactor()
    {
        $user = Auth::user();
        $user->two_factor_secret = null;
        $user->two_factor_recovery_codes = null;
        $user->two_factor_confirmed_at = null;
        $user->save();
        $this->dispatch('done', success: "Two Factor Authentication Disabled");
    }
}; ?>

<div>
    <section class="w-full">
        @include('partials.settings-heading')

        <x-settings.layout :heading="__('Two Factor Authentication')" :subheading="__('Enable/Disable Two Factor Authentication')">
            @if (!Auth::user()->two_factor_secret)
            @if ($showingQrCode)
            <div class="mt-4 space-y-4">
                <p class="text-zinc-700 dark:text-zinc-200">Scan the QR Code with your Authenticator App</p>
                {!! $qrCodeUrl !!}

                <flux:input wire:model="code" type="text" label="Enter the Code Generated by the Authenticator App"></flux:input>
                <flux:error namel="code"></flux:error>

                <div class="grid grid-cols-2 gap-4">
                    <flux:button variant="primary" wire:click="enableTwoFactor" class="w-full">
                        {{ __('Enable Two Factor Authentication') }}
                    </flux:button>
                    <flux:button variant="danger" wire:click="toggleQrCode" class="w-full">
                        {{ __('Hide QR Code') }}
                    </flux:button>

                </div>
            </div>
            @else

            <div class="mt-4 space-y-4">
                <p class="text-zinc-700 dark:text-zinc-200">Click the button below to show the QR Code</p>
                <flux:button variant="primary" wire:click="toggleQrCode" class="w-full">
                    {{ __('Show QR Code') }}
                </flux:button>
            </div>

            @endif

            @else

            <div class="mt-4 space-y-4">
                <p class="text-zinc-700 dark:text-zinc-200">Your Two Factor Authentication is enabled</p>
                <flux:button variant="danger" wire:click="disableTwoFactor" class="w-full">
                    {{ __('Disable Two Factor Authentication') }}
                </flux:button>
                @if (!$showingRecoveryCodes)
                <flux:button variant="primary" wire:click="toggleRecoveryCodes" class="w-full">
                    {{ __('Show Recovery Codes') }}
                </flux:button>
                @else
                <ul class="space-y-2 grid grid-cols-2 gap-2">
                    @foreach (json_decode($recoveryCodes) as $code)
                    <li>{{ $code }}</li>
                    @endforeach
                </ul>

                <flux:button variant="danger" wire:click="toggleRecoveryCodes" class="w-full">
                    {{ __('Hide Recovery Codes') }}
                </flux:button>
                @endif

                @endif

        </x-settings.layout>
    </section>
</div>
